name: Generate 3D Profile Card

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D profile card
        uses: jasonlong/gh-profile-card@v1
        with:
          user: Sanduni204
          theme: dark

      - name: Move output to profile-3d-contrib folder
        run: |
          mkdir -p profile-3d-contrib
          mv card.svg profile-3d-contrib/profile-3d.svg

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated 3D Profile Card"
          file_pattern: "profile-3d-contrib/**"
