name: GitHub Profile 3D Contrib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate 3D profile contribution tiles
        uses: moke-dev/github-profile-3d-contrib@main
        with:
          username: Sanduni204

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated 3D Profile Card"
          file_pattern: "profile-3d-contrib/**"
